sonar.projectKey=Javiruizg_LifeTime
sonar.organization=javiruizg
sonar.projectName=LifeTime
sonar.sourceEncoding=UTF-8

sonar.sources=server/src,app
sonar.tests=server/src,app

sonar.test.inclusions=server/src/**/*.test.ts,app/**/*.test.ts,app/**/*.test.tsx
sonar.exclusions=node_modules/**,server/node_modules/**,app/node_modules/**,server/dist/**,app/.expo/**,app/ios/**,app/android/**

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info,app/coverage/lcov.info
