export const theme = {
  colors: {
    primary: '#c65f1eff',
    primaryLight: '#2a4f7a',
    primaryDark: '#152a45',
    secondary: '#1eba06ff',
    secondaryLight: '#fb923c',
    secondaryDark: '#ea580c',
    background: '#1e3a5f',
    surface: '#ffffff',
    surfaceAlt: '#f8fafc',
    text: '#1e293b',
    textSecondary: '#64748b',
    textMuted: '#94a3b8',
    border: '#e2e8f0',
    danger: '#ef4444',
    dangerLight: '#fca5a5',
    success: '#22c55e',
    white: '#ffffff',
    overlay: 'rgba(30, 58, 95, 0.08)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 9999,
  },
  shadows: {
    sm: {
      shadowColor: '#1e3a5f',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#1e3a5f',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#1e3a5f',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 6,
    },
  },
};
